### ISSUE TITLE
Problem with Responsive one page design in javascript parts

### ISSUE THREAD

**Issue by bahmanian** [planetoftheweb/responsive#12]
Hello
after adding this code in the scrollmagic part of the project:	

	var controller = new ScrollMagic({
		globalSceneOptions: {
			triggerHook: "onLeave"
		}
	});
	
	var attractionstween = TweenMax.straggerFromTo('#attractions article', 1, {opacity: 0, scale: 0},{delay: 1,opacity: 1, scale:1, ease: Back.easeOut});
	
	var scene = new ScrollScene({
		triggerElement : '#attractions';
	}).setTween(attractionstween).addTo(controller);

when I run gulp in the cmd line to see my project in localhost,immediately I get this huge errors:

[21:31:03] { [SyntaxError: Unexpected token (111:33) while parsing C:\Users\Fars
heed\desktop\resback\components\scripts\fake_c323e8c3.js]
  plugin: 'gulp-browserify',
  showStack: false,
  name: 'SyntaxError',
  message: 'Unexpected token (111:33) while parsing C:\\Users\\Farsheed\\desktop
\\resback\\components\\scripts\\fake_c323e8c3.js',
  fileName: undefined,
  lineNumber: undefined,
  stack: 'SyntaxError: Unexpected token (111:33) while parsing C:\\Users\\Farshe
ed\\desktop\\resback\\components\\scripts\\fake_c323e8c3.js\n    at Stream.end (
C:\\Users\\Farsheed\\desktop\\resback\\node_modules\\insert-module-globals\\inde
x.js:71:21)\n    at _end (C:\\Users\\Farsheed\\desktop\\resback\\node_modules\\t
hrough\\index.js:65:9)\n    at Stream.stream.end (C:\\Users\\Farsheed\\desktop\\
resback\\node_modules\\through\\index.js:74:5)\n    at Transform.onend (C:\\User
s\\Farsheed\\desktop\\resback\\node_modules\\module-deps\\node_modules\\through2
\\node_modules\\readable-stream\\lib\\_stream_readable.js:523:10)\n    at Transf
orm.g (events.js:273:16)\n    at emitNone (events.js:85:20)\n    at Transform.em
it (events.js:179:7)\n    at C:\\Users\\Farsheed\\desktop\\resback\\node_modules
\\module-deps\\node_modules\\through2\\node_modules\\readable-stream\\lib\\_stre
am_readable.js:965:16\n    at nextTickCallbackWith0Args (node.js:452:9)\n    at
process._tickCallback (node.js:381:13)' }

how I can fix this?

**Comment by bahmanian** [comment]
Fortunately I could fix that..
